# Generated by Django 5.2.8 on 2025-11-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_footertext'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='footertext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='locale',
        ),
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
