# Generated by Django 5.2.8 on 2025-11-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_blogpage_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='authors',
        ),
    ]
